#!/usr/bin/env bash

set -e

# ---------------

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

META_DIR="${BASE_DIR}/meta"

# ---------------

QUIET=false
VERBOSE=0
while getopts :hqv opt 2>/dev/null; do
    case $opt in
    h)
        show_help
        exit
        ;;
    q)
        QUIET=true
        ;;
    v)
        VERBOSE=1
        ;;
    :)
        echo "Missing argument for option -$OPTARG"
        exit 1
        ;;
    ?)
        echo "Unknown option -$OPTARG"
        exit 1
        ;;
    esac
done

[ $QUIET ] && echo -e "quiet mode on"
[ $VERBOSE ] && echo -e "verbose mode on"

BIN_DOTBOT="${BASE_DIR}/modules/dotbot/bin/dotbot $([ $QUIET ] && echo "-q") $([ $VERBOSE ] && echo "-v") -d ${BASE_DIR}"
BIN_OSDETECT="${BASE_DIR}/bin/osdetection"

# ---------------

. "$BIN_OSDETECT"

# detect user defined dotfiles profile
if [ -z "${1+x}" ]; then
    if [ -f ~/.dotfiles.use_profile ]; then
        PROFILE_NAME=$(cat ~/.dotfiles.use_profile)
    else
        PROFILE_NAME="workstation"
        $QUIET && echo "${PROFILE_NAME}" >~/.dotfiles.use_profile
    fi
else
    PROFILE_NAME="$1"
    $QUIET && echo "${PROFILE_NAME}" >~/.dotfiles.use_profile
    shift
fi

$QUIET && echo -e "=========\nConfigure profile ${PROFILE_NAME} for os ${OS_SHORT}\n"
$QUIET && echo -e "   - os-base: ${OS_BASE}"
$QUIET && echo -e "   - os: ${OS_SHORT}"
systemRoles=(
    "${OS_BASE}"
    "${OS_BASE}_${OS_SHORT}"
)

if [ "$OS_IS_WSL" = "wsl" ]; then
    systemRoles+=("${OS_BASE}_${OS_SHORT}_wsl")
    $QUIET || echo -e "   - subsystem: ${OS_IS_WSL}"
fi

echo -e "\n=========\n"

# ---------------

cd "${BASE_DIR}"
git submodule update --init --recursive --remote

bash -c "${BIN_DOTBOT} -c ${META_DIR}/main.yml"

for systemRole in "${systemRoles[@]}"; do

    bash -c "${BIN_DOTBOT} -c ${META_DIR}/${systemRole}/main.yml"

    profile="${META_DIR}/${systemRole}/profiles/${PROFILE_NAME}"
    if [ -f "${profile}" ]; then
        while IFS= read -r pack; do
            if [[ $pack != *"#"* ]]; then
                $QUIET || echo -e "\nConfigure pack ${pack} for ${systemRole}"
                bash -c "${BIN_DOTBOT} -c ${BASE_DIR}/packs/${pack}/main.yml"
            fi
        done <"${profile}"
    fi
done
