#!/usr/bin/env bash

set -e

OSTYPE_IS_WSL=false
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    OSTYPE_BASE="unix"; OSTYPE_SHORT="linux"

    if [[ "$(uname -r)" =~ "Microsoft" ]]; then
        # WSL (Windows Subsystem for Linux; Bash for Windows)
        OSTYPE_IS_WSL=true
    fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    OSTYPE_BASE="unix"; OSTYPE_SHORT="macos"
elif [[ "$OSTYPE" == "cygwin" ]]; then
    # POSIX compatibility layer and Linux environment emulation for Windows
    exit 1
elif [[ "$OSTYPE" == "msys" ]]; then
    # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
    exit 1
elif [[ "$OSTYPE" == "win32" ]]; then
    # I'm not sure this can happen.
    exit 1
elif [[ "$OSTYPE" == "freebsd"* ]]; then
    # ...
    exit 1
else
    # Unknown.
    exit 1
fi

# ---------------

BASE_CONFIG="base"
CONFIG_SUFFIX=".yml"

META_DIR="meta"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="modules/dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ ! -z "${1+x}" ] && [ "-q" == "$1" ]; then
    QUIET=true
    shift
else
    QUIET=false
fi

if [ -z "${1+x}" ]; then
    if [ -f ~/.dotfiles.use_profile ]; then
        PROFILE_NAME=$(cat ~/.dotfiles.use_profile)
    else
        PROFILE_NAME="workstation"
        echo "${PROFILE_NAME}" > ~/.dotfiles.use_profile
    fi
else
    PROFILE_NAME="$1"
    echo "${PROFILE_NAME}" > ~/.dotfiles.use_profile
    shift
fi
echo -e "=========\nConfigure profile ${PROFILE_NAME} for os ${OSTYPE_SHORT}\n=========\n"

# ---------------

cd "${BASE_DIR}"
git submodule update --init --recursive --remote

metaSubDirs=(
    "${OSTYPE_BASE}"
    "${OSTYPE_BASE}_${OSTYPE_SHORT}"
)

if [ "$OSTYPE_IS_WSL" = true ]; then
    metaSubDirs+=("${OSTYPE_BASE}_${OSTYPE_SHORT}_wsl")
fi

for metaSub in "${metaSubDirs[@]}"; do
    CONFIGS=""
    if [ -f "${META_DIR}/${metaSub}/${PROFILES_DIR}/${PROFILE_NAME}" ]; then
        while IFS= read -r config; do
            CONFIGS+=" ${config}"
        done < "${META_DIR}/${metaSub}/${PROFILES_DIR}/${PROFILE_NAME}"
    fi

    "${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "${META_DIR}/${metaSub}/${BASE_CONFIG}${CONFIG_SUFFIX}" $($QUIET && echo "-q")

    for config in ${CONFIGS} ${@}; do
        $QUIET || echo -e "\nConfigure ${config} for ${metaSub}"
        "${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "${META_DIR}/${metaSub}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}" $($QUIET && echo "-q")
    done
done