- shell:
    -
        command: cp extra/fonts/**/*.(ttf|otf) ~/Library/Fonts/
#    ~/Library/Fonts/:
#        glob: true
#        path: extra/fonts/*/*.(ttf|otf)
#        relink: true
#    ~/Library/Fonts/:
#        glob: true
#        path: extra/fonts/FiraMono for Powerline/*.otf
#        relink: true
