- defaults:
      link:
          create: true
          relink: true
          force: true

- link:
    ~/.oh-my-zsh: modules/oh-my-zsh
    ~/.zshrc: dotfiles/.zshrc

- shell:
    -
        command: test -x /bin/zsh && sudo chsh -s /bin/zsh $(whoami) || echo "skipped because zsh is not installed"
        stdin: true
        stdout: true
        stderr: true
        description: Setting ZSH as default shell
    -
        command: test -x /bin/zsh && compaudit | xargs chmod g-w,o-w || echo "skipped because zsh is not installed"
        description: Fixing file permissions of oh-my-zsh
        
